# Generated by Django 4.0.3 on 2022-03-21 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_todos_update_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todos',
            name='update_date',
        ),
    ]
