# Generated by Django 4.0.3 on 2022-03-21 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_remove_todos_update_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='todos',
            name='update_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
