# Generated by Django 4.0.3 on 2022-03-21 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_alter_todos_update_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todos',
            name='update_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
