# Generated by Django 4.0.3 on 2022-03-21 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_alter_todos_update_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owners', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.todos')),
            ],
        ),
    ]
