# Generated by Django 4.0.3 on 2022-03-22 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_owner'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Owner',
        ),
    ]
