# Generated by Django 4.0.3 on 2022-03-22 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_delete_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todos',
            name='update_date',
        ),
    ]
